export interface GunDetailsViewModel {
    id: string,
    name: string,
    manufacturer: string,
    imageUrl: string,
    power: number,
    color: string,
    weight: number,
    magazine: string,
    capacity: number,
    speed: number,
    firing: string,
    length: number,
    barrel: number,
    propulsion: string,
    material: string,
    blowback: string,
    hopup: string,
    price: number,
    dealerName: string,
    dealerUrl: string,
    dealerId: string
}